---
apiVersion: v1
kind: Service
metadata:
  name: irohaboard-service
  labels:
    app: irohaboard
spec:
  type: ClusterIP
  ports:
    - name: irohaboard
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: irohaboard
    tier: frontend
