apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: {{ .Values.storageSize.pv }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath.path }}
    type: DirectoryOrCreate
